# Generated by Django 3.0.3 on 2020-07-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumes',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.RenameField(
            model_name='resumes',
            old_name='date',
            new_name='date_pub',
        ),
        migrations.AlterField(
            model_name='resumes',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='file',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.CreateModel(
            name='Resume_Information_Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='resume_pics')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final.Resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_text', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Final.Resumes')),
            ],
            options={
                'verbose_name': 'Uploaded Resume',
                'verbose_name_plural': 'Uploaded Resumes',
            },
        ),
    ]
