# Generated by Django 3.0.3 on 2020-03-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0002_auto_20200311_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumes',
            old_name='date',
            new_name='date_pub',
        ),
    ]
