# Generated by Django 3.0.3 on 2020-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0003_auto_20200923_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_information',
            name='pdf_text',
            field=models.TextField(),
        ),
    ]
