# Generated by Django 3.0.3 on 2020-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0005_auto_20200923_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_information',
            name='rating',
            field=models.FloatField(),
        ),
    ]
