# Generated by Django 3.0.3 on 2020-09-24 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0007_auto_20200924_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_information',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 14, 26, 6, 639286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 14, 26, 6, 599118, tzinfo=utc)),
        ),
    ]
