# Generated by Django 3.0.3 on 2020-09-25 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Final', '0008_auto_20200924_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_information',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='date_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
